{% set name = "ci-info" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mgxd/ci-info/archive/{{ version }}.tar.gz
  sha256: 7d112cfd38b7e80ba1fe4e9e494dd6d2c482ac4fc3aa93c1f931ab455f324284

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - ci_info
    - ci_info.tests

about:
  home: https://github.com/mgxd/ci-info
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Get details about the current Continuous Integration environment.

  # doc_url: 
  dev_url: https://github.com/mgxd/ci-info

extra:
  recipe-maintainers:
    - mgxd
    - satra
    - effigies
