schema_version: 1

context:
  name: ci-info
  version: 0.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/mgxd/ci-info/archive/${{ version }}.tar.gz
  sha256: 92a10ecca1bbee479bac86cd72c2922d6ff1aa015e40b52246bcf9972a411ff3

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - ci_info
        - ci_info.tests
      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE
  summary: Get details about the current Continuous Integration environment.
  # doc_url:
  homepage: https://github.com/mgxd/ci-info
  repository: https://github.com/mgxd/ci-info

extra:
  recipe-maintainers:
    - mgxd
    - satra
    - effigies
